# Generated by Django 3.2.8 on 2021-10-07 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Humon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
                ('description', models.TextField(verbose_name='о нем')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актeры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=255, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movies/', verbose_name='постер')),
                ('year', models.PositiveSmallIntegerField(default=2021, verbose_name='Дата выхода')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('world', models.DateField(default=datetime.date.today, verbose_name='Примьера в мире')),
                ('budjet', models.PositiveIntegerField(default=0, help_text='укажите сумму в Долларах', verbose_name='Бюджет')),
                ('fees_in_usa', models.PositiveIntegerField(default=0, help_text='СЧборы в США', verbose_name='Сборы в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='СЧборы в мире', verbose_name='Сборы в США')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('actors', models.ManyToManyField(to='Movie.Humon', verbose_name='Актер')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Movie.category', verbose_name='Категория')),
                ('directors', models.ManyToManyField(related_name='film_director', to='Movie.Humon', verbose_name='Режисер')),
                ('genres', models.ManyToManyField(to='Movie.Genre', verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.TextField(blank=True, verbose_name='Отзывы')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Movie.movie', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Movie.review', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Ratingstar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volue', models.SmallIntegerField(default=0, verbose_name='значение')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Звёзды рейтингов',
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='movies/shots/', verbose_name='Стоп кадр')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Кадры из фильмов',
            },
        ),
    ]
